# 6 NumPy Coding Problems


1. Create a null vector of size 10 but the fifth value which is 1.

In [1]:
import numpy as np

null_vector = np.zeros(10)
null_vector[4] = 1

print(null_vector)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


2. Create a vector with values ranging from 10 to 49.

In [2]:
import numpy as np

vector = np.arange(10, 50)

print(vector)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


3. Create a 3x3 matrix with values ranging from 0 to 8

In [3]:
import numpy as np

matrix = np.arange(9).reshape(3, 3)

print(matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [4]:
import numpy as np

arr = np.array([1, 2, 0, 0, 4, 0])

non_zero_indices = np.nonzero(arr)

print(non_zero_indices)


(array([0, 1, 4]),)


5. Create a 10x10 array with random values and find the minimum and maximum values.

In [6]:
import numpy as np

# Create a 10x10 array with random values
random_array = np.random.random((10, 10))

# Find the minimum and maximum values
min_value = np.min(random_array)
max_value = np.max(random_array)

print("Random Array:")
print(random_array)
print("Minimum Value:", min_value)
print("Maximum Value:", max_value)


Random Array:
[[0.74228647 0.14603548 0.81719551 0.01453686 0.12841256 0.72158787
  0.69265148 0.30635494 0.53721441 0.91947395]
 [0.40358079 0.58923301 0.19392939 0.13040806 0.42533502 0.20934856
  0.27592399 0.86886932 0.18280425 0.30433428]
 [0.74555562 0.68312422 0.45150401 0.95115704 0.4444851  0.80172539
  0.13516716 0.75117934 0.07529138 0.73044097]
 [0.72049107 0.78900393 0.55353398 0.01644605 0.24694842 0.90103795
  0.28098054 0.3321705  0.80171764 0.71994537]
 [0.77896302 0.43092746 0.0406672  0.96257847 0.07705764 0.01186808
  0.12540523 0.52692461 0.7139664  0.78298968]
 [0.75528792 0.37369528 0.62230384 0.00495239 0.32482451 0.30624178
  0.43002003 0.89901618 0.80066115 0.10019041]
 [0.27978036 0.51900949 0.09438877 0.86826049 0.90470889 0.62323801
  0.9266748  0.49204406 0.33604503 0.07041631]
 [0.62715639 0.56429043 0.78154525 0.94522542 0.23793644 0.24293903
  0.65407415 0.97559929 0.58983251 0.3453085 ]
 [0.91988873 0.93146078 0.6986921  0.57025204 0.81969814 0.2716733

6. Create a random vector of size 30 and find the mean value.


In [7]:
import numpy as np

# Create a random vector of size 30
random_vector = np.random.random(30)

# Find the mean value
mean_value = np.mean(random_vector)

print("Random Vector:")
print(random_vector)
print("Mean Value:", mean_value)


Random Vector:
[0.9827949  0.89830293 0.96803925 0.57545623 0.34304873 0.78415818
 0.33535838 0.62080052 0.10345154 0.43155748 0.88481341 0.72370226
 0.74548105 0.11243929 0.11153981 0.41378426 0.14731533 0.74036008
 0.22774493 0.99947021 0.13400559 0.50129968 0.95431873 0.93656636
 0.60075302 0.53819418 0.99565783 0.28764715 0.85307528 0.03059259]
Mean Value: 0.5660576393361345
